name: Node.js CI
on:
  push:
    branches: [ main ] #监听master分支的push事件
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest #指定运行环境为最新的Ubuntu版本
    strategy:
      matrix:
        node-version: [16.15.0] #指定node版本
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} #使用action安装node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install #安装项目依赖
    - run: npm run build #build项目
    - run: apt install sshpass
    - run: sshpass -p ${{ secrets.PASSWORD }} ssh ${{ secrets.USER }@${{ secrets.HOST }} "/root/myroom-server/deploy.sh"
